""" THIS SCRIPT IS VALID BASED ON THE SINGAPORE MRT MAP VERSION ON 20 SEPTEMBER 2018. """

"""
LINE NO              LINE
   1                 EAST WEST LINE
   2                 NORTH SOUTH LIKE
   3                 CIRCLE LINE
   4                 NORTH EAST LINE
   5                 DOWNTOWN LINE
   6                 CIRCLE LINE BRANCH
   7                 AIRPORT BRANCH
   8                 BUKIT PANJANG LRT
   9                 SENKANG LRT WEST
   10                SENKANG LRT EAST
   11                PUNGGOL LRT WEST
   12                PUNGGOL LRT EAST
"""

# Display name of station in data
# When checking with input call .upper
data = {
         1 : {
                 1:["Pasir Ris",[]]
                 2:["Tampines",[5]]
                 3:["Simei",[]]
                 4:["Tanah Merah",[7]]
                 5:["Bedok",[]]
                 6:["Kembangan",[]]
                 7:["Eunos",[]]
                 8:["Paya Lebar",[3]]
                 9:["Aljunied",[]]
                 10:["Kallang",[]]
                 11:["Lavender",[]]
                 12:["Bugis",[5]]
                 13:["City Hall",[2]]
                 14:["Raffles Place",[2]]
                 15:["Tanjong Pagar",[]]
                 16:["Outram Park",[4]]
                 17:["Tiong Bahru",[]]
                 18:["Redhill",[]]
                 19:["Queenstown",[]]
                 20:["Commonwealth",[]]
                 21:["Buona Vista",[3]]
                 22:["Dover",[]]
                 23:["Clementi",[]]
                 24:["Jurong East",[2]]
                 25:["Chinese Garden",[]]
                 26:["Lakeside",[]]
                 27:["Boon Lay",[]]
                 28:["Pioneer",[]]
                 29:["Joo Koon",[]]
                 30:["Gul Circle",[]]
                 31:["Tuas Crescent",[]]
                 32:["Tuas West Road",[]]
                 33:["Tuas Link",[]]
             }
         2 : {
                 1:["Jurong East",[1]]
                 2:["Bukit Batok",[]]
                 3:["Bukit Gombak",[]]
                 4:["Choa Chu Kang",[8]]
                 5:["Yew Tee",[]]
                 6:[None,[]]
                 7:["Kranji",[]]
                 8:["Marsiling",[]]
                 9:["Woodlands",[]]
                 10:["Admiralty",[]]
                 11:["Sembawang",[]]
                 12:[None,[]]
                 13:["Yishun",[]]
                 14:["Khatib",[]]
                 15:["Yio Chu Kang",[]]
                 16:["Ang Mo Kio",[]]
                 17:["Bishan",[3]]
                 18:["Braddell",[]]
                 19:["Toa Payoh",[]]
                 20:["Novena",[]]
                 21:["Newton",[5]]
                 22:["Orchard",[]]
                 23:["Somerset",[]]
                 24:["Dhoby Ghaut",[3,4]]
                 25:["City Hall",[1]]
                 26:["Raffles Place",[1]]
                 27:["Marina Bay",[6]]
                 28:["Marina South Pier",[]]
             }
         3 : {
                 1:["Dhoby Ghaut",[2,4]]
                 2:["Bras Basah",[]]
                 3:["Esplanade",[]]
                 4:["Promenade",[5,6]]
                 5:["Nicoll Highway",[]]
                 6:["Stadium",[]]
                 7:["Mountbatten",[]]
                 8:["Dakota",[]]
                 9:["Paya Lebar",[1]]
                 10:["MacPherson",[5]]
                 11:["Tai Seng",[]]
                 12:["Bartley",[]]
                 13:["Serangoon",[4]]
                 14:["Lorong Chuan",[]]
                 15:["Bishan",[2]]
                 16:["Marymount",[]]
                 17:["Caldecott",[]]
                 18:[None,[]]
                 19:["Botanical Gardens",[5]]
                 20:["Farrer Road",[]]
                 21:["Holland Village",[]]
                 22:["Buona Vista",[1]]
                 23:["one-north",[]]
                 24:["Kent Ridge",[]]
                 25:["Haw Par Villa",[]]
                 26:["Pasir Panjang",[]]
                 27:["Labrador Park",[]]
                 28:["Telok Blangah",[]]
                 29:["HarbourFront",[4]]
             }
         4 : {
                 1:["HarbourFront",[3]]
                 2:[None,[]]
                 3:["Outram Park",[1]]
                 4:["Chinatown",[5]]
                 5:["Clarke Quay",[]]
                 6:["Dhoby Ghaut",[2,3]]
                 7:["Little India",[5]]
                 8:["Farrer Park",[]]
                 9:["Boon Keng",[]]
                 10:["Potong Pasir",[]]
                 11:["Woodleigh",[]]
                 12:["Serangoon",[3]]
                 13:["Kovan",[]]
                 14:["Hougang",[]]
                 15:["Buangkok",[]]
                 16:["Sengkang",[9,10]]
                 17:["Punggol",[11,12]]
             }
         5 : {
                 1:["Bukit Panjang",[8]]
                 2:["Cashew",[]]
                 3:["Hillview",[]]
                 4:[None,[]]
                 5:["Beauty World",[]]
                 6:["King Albert Park",[]]
                 7:["Sixth Avenue",[]]
                 8:["Tan Kah Kee",[]]
                 9:["Botanic Gardens",[3]]
                 10:["Stevens",[]]
                 11:["Newton",[2]]
                 12:["Little India",[4]]
                 13:["Rocher",[]]
                 14:["Bugis",[1]]
                 15:["Promenade",[3,6]]
                 16:["Bayfront",[6]]
                 17:["Downtown",[]]
                 18:["Telok Ayer",[]]
                 19:["Chinatown",[4]]
                 20:["Fort Canning",[]]
                 21:["Bencoolen",[]]
                 22:["Jalan Besar",[]]
                 23:["Bendemeer",[]]
                 
